# Netlify build configuration for React SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Build settings
[build]
  base = "frontend"
  publish = "build"
  command = "npm ci && npm run build"

# Node.js version specification
[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8"
  CI = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"

# Environment variables will be set in Netlify dashboard