# Netlify build configuration for React SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Build settings
[build]
  base = "frontend"
  publish = "build"
  command = "npm install && npm install ajv@^8.0.0 --save-dev && GENERATE_SOURCEMAP=false CI=false npm run build"

# Node.js version specification
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"

# Environment variables will be set in Netlify dashboard