# Netlify build configuration for React SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Build settings
[build]
  base = "frontend"
  publish = "frontend/build"
  command = "CI=false npm run build"

# Node.js version specification
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Environment variables will be set in Netlify dashboard